---
# tasks file for myApache

    - name: Updates apt cache
      apt: update_cache=true

    - name: Installs necessary packages
      apt:
        pkg: "{{ item }}"
        state: latest
      loop:
        '{{ apache_packages }}'

    - name: Push future default virtual host configuration
      copy:
        src: '{{ config }}'
        dest: /etc/apache2/sites-available/'{{ config }}'.conf
        mode: "0640"

    - name: Activates our virtualhost
      command: a2ensite '{{ config }}'

    - name: Check that our config is valid
      command: apache2ctl configtest
      register: result
      ignore_errors: true

    - name: Rolling back - Restoring old default virtualhost
      command: a2ensite 000-default
      when: result is failed

    - name: Rolling back - Removing our virtualhost
      command: a2dissite '{{ config }}'
      when: result is failed

    - name: Rolling back - Ending playbook
      fail:
        msg: "Configuration file is not valid. Please check that before re-running the playbook."
      when: result is failed

    - name: Deploy our awesome application
      git:
        repo: https://github.com/leucos/ansible-tuto-demosite.git
        dest: /var/www/'{{ appDir }}'
      tags: deploy

    - name: Deactivates the default virtualhost
      command: a2dissite 000-default

    - name: Deactivates the default SSL virtualhost
      command: a2dissite default-ssl
      notify:
        - restart apache
