---
# tasks file for java'{{ compiledFileName }}'

    - name: Ensure necessary packages is installed on node2 
      apt:
        pkg: "{{ item }}"
        state: latest
      loop:
        - default-jdk
        - git
      when: "'java' in group_names"

    - name: Clone Java repository on node2
      git:
        repo: '{{ repo }}'
        dest: '{{ repoDir }}'
      when: inventory_hostname == 'node2'

    - name: Compile Java application on node2
      command: javac '{{ compiledFileName }}'.java
      args:
        chdir: '{{ repoDir }}'
      when: inventory_hostname == 'node2'

    - name: Fetch compiled Java files to controller
      fetch:
        src: '{{ repoDir }}/{{ compiledFileName }}.class'
        dest: '{{ compiledFileDir }}/{{ compiledFileName }}.class'
        flat: yes
      when: inventory_hostname == 'node2'

    - name: Ensure runDir directory exists on node3
      file:
        path: '{{ runDir }}'
        state: directory
      when: inventory_hostname == 'node3'

    - name: Copy compiled Java files to node3
      copy:
        src: '{{ compiledFileDir }}/{{ compiledFileName }}.class'
        dest: '{{ runDir }}/{{ compiledFileName }}.class'
      when: inventory_hostname == 'node3'

    - name: Ensure Java is installed on node3
      apt:
        name: default-jdk
        state: present
      when: inventory_hostname == 'node3'

    - name: Run Java application on node3
      command: java '{{ compiledFileName }}'
      args:
        chdir: '{{ runDir }}'
      register: java_output
      when: inventory_hostname == 'node3'
      
    - name: Display Java output on localhost
      debug:
        msg: "{{ java_output.stdout }}"
      when: inventory_hostname == 'node3'
