---
# vars file for javaHelloWorld

repo:
  https://github.com/LuisJoseSanchez/hello-world-java.git
  
repoDir:
  /tmp/hello-world-java
  
compiledFileName:  
  HelloWorld
  
compiledFileDir:
  /tmp
  
runDir:
  /opt/java-app
